language: php
dist: trusty

php:
  - 7.4
  - 8.0
  - 8.1

env:
  global:
    - setup=basic
install:
  - travis_retry composer install --no-interaction

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
