language: php
dist: focal

php:
  - 7.4
  - 8.0
  - 8.1

install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
